# Generated by Django 4.0.2 on 2022-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('inn', models.BigIntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('extraPhones', models.CharField(blank=True, max_length=50)),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('refImages', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
