# Generated by Django 4.0.2 on 2022-02-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('NE', 'Новый'), ('US', 'Б/У')], default='NE', max_length=2)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
