# Generated by Django 4.0.2 on 2022-02-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('New', 'Новый'), ('Used', 'Б/У')], default='New', max_length=4),
        ),
    ]
