# Generated by Django 4.0.2 on 2022-02-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtsale',
            name='status',
            field=models.CharField(choices=[('Paid', 'Оплачено'), ('Not_Paid', 'Не оплачено')], default='Not_Paid', max_length=8),
        ),
    ]
